=== ABEL003/Studium/3.Semester/Datenmanagement/Strukturieren in XML/Aufgabe1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dozentenliste">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="dozent" type="dozent_typ" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="dozent_typ">
  <xs:sequence>
    <xs:element name="name" type="xs:string"/>
    <xs:element name="vorname" type="xs:string"/>
    <xs:element name="bild" type="bild_type"/>
    <xs:element name="aktuelles" type="xs:string"/>
  </xs:sequence>
  <xs:attribute name="did" type="xs:string"/>
  <xs:attribute name="anrede" type="xs:string"/>
</xs:complexType>

<xs:complexType name="bild_type">
  <xs:simpleContent>
    <xs:extension base="xs:string">
      <xs:attribute name="ref" type="xs:string"/>
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>

</xs:schema>

=== ABEL003/Studium/3.Semester/Datenmanagement/Strukturieren in XML/Aufgabe1.xml
<?xml version="1.0" encoding="UTF-8"?>
<dozentenliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe1.xsd">
    <dozent did="d1" anrede="Herr">
        <name>Maier</name>
        <vorname>Fritz</vorname>
        <bild ref="maier.jpg"/>
        <aktuelles>Nächste Woche findet die Sprechstunde am Montag statt. </aktuelles>
    </dozent> <dozent did="d2" anrede="Frau">
        <name>Müller</name>
        <vorname>Sabine</vorname>
        <bild ref="mueller.jpg"/>
        <aktuelles>Heute: Vortrag zum Thema &quot;Auslandsstudium&quot; </aktuelles>
    </dozent>
</dozentenliste>
